name: Issue Event Info

on:
  issues:
    types: [opened, edited]

jobs:
  show-issue-details:
    runs-on: ubuntu-latest
    steps:
      - name: Print issue title
        run: echo "${{ github.event.issue.title }} "
      
      - name: Print issue number
        run: echo "${{ github.event.issue.number }}"
      
      - name: Print issue body
        run: echo "${{ github.event.issue.body }}"
      
      - name: Print issue author
        run: echo "${{ github.event.issue.user.login }}"

      - name: Dump event payload
        run: cat $GITHUB_EVENT_PATH
