name: Push workflow
on: push
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  Install_NodeJs:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - uses: actions/setup-node@v3.9.1
      with:
        node-version: '22.x'
    - name: Install Dependencies
      run: npm install
  Run_Lint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: Install_NodeJs
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Run lint
      run: npm run lint
  Run_Test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: Install_NodeJs
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Run test
      run: npm run test
  Run_Deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: Install_NodeJs
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Run deploy
      run: npm run deploy
